backend:
  name: git-gateway

media_folder: src/pages/images
public_folder: src/pages/images

collections:
  - name: blog
    label: Blog
    folder: src/pages/posts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }